### ISSUE TITLE
选择电子表格形式导出，Excel无法打开

### ISSUE THREAD

**Issue by EngChiJap** [bmqy/qq-group-manager#28]
如题。
可能下载的文件损坏了？

**Comment by bmqy** [comment]
> 如题。 可能下载的文件损坏了？

QQ群改版了，目前应该是只能看到自己创建的和管理的群，加入的群看不到。
你现在还能看到插件的导出界面吗？

**Comment by EngChiJap** [comment]
可以看到导出界面，也可以复制到粘贴板导出




当时明月在
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bmqy/qq-group-manager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 上午8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28)





  
如题。 可能下载的文件损坏了？
  
QQ群改版了，目前应该是只能看到自己创建的和管理的群，加入的群看不到。
 你现在还能看到插件的导出界面吗？

**Comment by bmqy** [comment]
> 可以看到导出界面，也可以复制到粘贴板导出 当时明月在 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bmqy/qq-group-manager" ***@***.***&gt;; 发送时间:&nbsp;2023年11月24日(星期五) 上午8:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28) 如题。 可能下载的文件损坏了？ QQ群改版了，目前应该是只能看到自己创建的和管理的群，加入的群看不到。 你现在还能看到插件的导出界面吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我现在在新版QQ群页面看不到插件面板，看来需要更新了，等有时间更新下吧

**Comment by EngChiJap** [comment]
期待大佬的更新，大佬辛苦了




当时明月在
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bmqy/qq-group-manager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28)





  
可以看到导出界面，也可以复制到粘贴板导出 当时明月在 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bmqy/qq-group-manager" @.&gt;; 发送时间:&nbsp;2023年11月24日(星期五) 上午8:39 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28) 如题。 可能下载的文件损坏了？ QQ群改版了，目前应该是只能看到自己创建的和管理的群，加入的群看不到。 你现在还能看到插件的导出界面吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我现在在新版QQ群页面看不到插件面板，看来需要更新了，等有时间更新下吧

**Comment by bmqy** [comment]
已更新，本地测试没有问题，可以正常导出xlsx

**Comment by EngChiJap** [comment]
呃呃，下载出来还是打不开，而且之前可以把它转成csv格式打开，现在转成csv打开反而只有一个QQ号并重复几十行。



&nbsp;


当时明月在
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月30日(星期四) 上午9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28)





 
已更新，本地测试没有问题，可以正常导出xlsx

**Comment by bmqy** [comment]
> 呃呃，下载出来还是打不开，而且之前可以把它转成csv格式打开，现在转成csv打开反而只有一个QQ号并重复几十行。 &nbsp; 当时明月在 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月30日(星期四) 上午9:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28) 已更新，本地测试没有问题，可以正常导出xlsx — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

未发现你的这个问题，但是更新了3.0.1，上一版导出的会员数只会有一条；

会不会是你的群成员的信息有问题，可以只导出qq号字段试试看正不正常；

**Comment by EngChiJap** [comment]
我一直都只选择导出QQ号，回退到2.0.2版本正常了
&nbsp;


当时明月在
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月30日(星期四) 中午1:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28)





  
呃呃，下载出来还是打不开，而且之前可以把它转成csv格式打开，现在转成csv打开反而只有一个QQ号并重复几十行。 &nbsp; 当时明月在 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月30日(星期四) 上午9:56 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [bmqy/qq-group-manager] 选择电子表格形式导出，Excel无法打开 (Issue #28) 已更新，本地测试没有问题，可以正常导出xlsx — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
未发现你的这个问题，但是更新了3.0.1，上一版导出的会员数只会有一条；
 
会不会是你的群成员的信息有问题，可以只导出qq号字段试试看正不正常；

**Comment by bmqy** [comment]
我这试了好几个群导出来都没这个问题。你换其它群导出试试
